language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

sudo: false

install:
  - pip install --editable .
  - pip install -r dev-requirements.txt coveralls

branches:
  only:
    - master
    - test

script:
   - doit pyflakes
   - py.test

notifications:
    email:
        on_success: change
        on_failure: change
